services:
  - type: web
    name: momentmillionaer-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: momentmillionaer-db
          property: connectionString
      - key: NOTION_INTEGRATION_SECRET
        sync: false
      - key: NOTION_PAGE_URL
        sync: false
    healthCheckPath: /health

databases:
  - name: momentmillionaer-db
    databaseName: momentmillionaer
    user: momentmillionaer